version: '3.8'
services:
  postgres:
    image: postgres:15.0
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: learningDb
    ports:
      - "5959:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - springboot-network

networks:
  springboot-network:

volumes:
  pgdata:
