info.app:
  name: Oauth2 Learning
  version: 1.0
  description: API demo project with oauth2

spring:
  application:
    name: oauth
  codec:
    max-in-memory-size: 10MB

  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5959/learningDb
    password: password
    username: postgres

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:3939/login/oauth2/code/google
            scope: email, profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  port: 3939
  servlet:
    context-path: /
  forward-headers-strategy: native
  shutdown: graceful
  error:
    include-message: always

logging:
  level:
    org.springframework.security: TRACE
